# Generated by Django 4.1.4 on 2023-04-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_rename_amount_admission_details_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmissionform',
            name='address_proof',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='addmissionform',
            name='graducation',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='addmissionform',
            name='intermediate',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='addmissionform',
            name='matriculation',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='addmissionform',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='addmissionform',
            name='postgraducation',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='addmissionform',
            name='signature',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
