# Generated by Django 4.1.4 on 2023-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_alter_addmissionform_address_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmissionform',
            name='address_proof',
            field=models.FileField(blank=True, default='default.pdf', upload_to='photodoc'),
        ),
        migrations.AlterField(
            model_name='addmissionform',
            name='graducation',
            field=models.FileField(blank=True, default='default.pdf', upload_to='graducationdoc'),
        ),
        migrations.AlterField(
            model_name='addmissionform',
            name='intermediate',
            field=models.FileField(blank=True, default='default.pdf', upload_to='intermediatedoc'),
        ),
        migrations.AlterField(
            model_name='addmissionform',
            name='matriculation',
            field=models.FileField(blank=True, default='default.pdf', upload_to='matricdoc'),
        ),
        migrations.AlterField(
            model_name='addmissionform',
            name='photo',
            field=models.ImageField(blank=True, default='deafault.jpg', upload_to='photoimage'),
        ),
        migrations.AlterField(
            model_name='addmissionform',
            name='postgraducation',
            field=models.FileField(blank=True, default='default.pdf', upload_to='postgraducationdoc'),
        ),
        migrations.AlterField(
            model_name='addmissionform',
            name='signature',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='signatureimage'),
        ),
    ]
