# Generated by Django 4.1.4 on 2023-04-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_alter_addmissionform_address_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmissionform',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photoimage'),
        ),
    ]
