# Generated by Django 4.1.4 on 2023-04-22 20:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu', '0008_alter_addmissionform_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admission_Details',
            new_name='Admission_Status',
        ),
    ]
