# Generated by Django 4.1.4 on 2023-04-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_rename_admission_details_admission_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission_status',
            old_name='payment_id',
            new_name='amount',
        ),
    ]
