# Generated by Django 4.1.4 on 2023-04-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_rename_payment_id_admission_status_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission_status',
            old_name='amount',
            new_name='payment_id',
        ),
    ]
